  <?php echo $this->getContent(); ?>
  <br>
  <div class="container">
    <marquee> ยินดีต้อนรับเข้าสู่ระบบกิจกรรมนักศึกาษา หลักสูตรวิศวกรรมซอฟต์แวร์ </marquee>
  </div>
  <hr>
  <div class="jumbotron jumbotron-fluid">
    <div class="container">

      <h1 class="display-4"><img src="https://image.flaticon.com/icons/svg/305/305126.svg" alt="Responsive image" class="rounded-circle" width="7%"> &nbsp;Activity <strong>Software Engineering...</strong> </h1>
      <!-- <p class="lead">This is a modified jumbotron that occupies the entire horizontal space of its parent.</p> -->
    </div>
  </div>
  <div class="container">

      <div class="card-deck">
          <div class="card">
              <img class="card-img-top" src="https://scontent.fbkk10-1.fna.fbcdn.net/v/t1.0-9/11951133_992445984139262_3229199624147949435_n.jpg?_nc_eui2=v1%3AAeHvsCSU5B3bjnzoDvtcMr6ZRqdKB-S8tpbv6p7ZmJY-6wJLh-JbDsOIWT7Ig0jKT0BntgPpOqrEwymlplUnSco5I1KDlUQGeelipXGhiXdoyQ&oh=9c0b0e516a19d14383499cf9053b4e19&oe=5A6A2D38" alt="Card image cap">
            <div class="card-body">
              <h4 class="card-title">Card title</h4>
              <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
            </div>
            <div class="card-footer">
              <small class="text-muted">Last updated 3 mins ago</small>
            </div>
          </div>
          <div class="card">
            <img class="card-img-top" src="https://scontent.fbkk10-1.fna.fbcdn.net/v/t1.0-9/21317505_1384290361619145_1725091535410851802_n.jpg?_nc_eui2=v1%3AAeEWn0ltRoktP2aOK76HFhxF2HHi_ch6gZicVz3EofTHIDILp7GqTRAU07FFLudrLwsMYU2MJzQaKFReQcYKy4LsKjZXZYdpPUEsw1j_Wpff3Q&oh=4ef1c6a6670b9b9268a5b8525463e52e&oe=5A9FCE60" alt="Card image cap">
            <div class="card-body">
              <h4 class="card-title">Card title</h4>
              <p class="card-text">This card has supporting text below as a natural lead-in to additional content.</p>
            </div>
            <div class="card-footer">
              <small class="text-muted">Last updated 3 mins ago</small>
            </div>
          </div>
          <div class="card">
            <img class="card-img-top" src="https://scontent.fbkk10-1.fna.fbcdn.net/v/t1.0-9/18194183_1264163450298504_2151468628984950087_n.jpg?_nc_eui2=v1%3AAeEvRlC-js8EqNNcJDpdul82-kU7MlHPMlWQ3ovsf5Jdp-kXQhh4lhCxt2TBgTd19JO901ewwVTFAv1pQ83cWQ0lUjUFX6T-tBBA54sK6_zdUA&oh=5a750e6c366d352e1c3e35b676b2c45a&oe=5AAB42DD" alt="Card image cap">
            <div class="card-body">
              <h4 class="card-title">Card title</h4>
              <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This card has even longer content than the first to show that equal height action.</p>
            </div>
            <div class="card-footer">
              <small class="text-muted">Last updated 3 mins ago</small>
            </div>
          </div>
          </div>
          <br>

        <div class="card-deck">
            <div class="card">
              <img class="card-img-top" src="https://scontent.fbkk2-6.fna.fbcdn.net/v/t31.0-8/18278224_1283503158430472_2160470521013243685_o.jpg?_nc_eui2=v1%3AAeHtGVNf5Fz4wSpBz3sVBO3rkLqueaA_p1wR_6f4NOOBAG3THgVM63YB6Pe1nuVFuvRqlTS7zeffQ51dTiYeNhvK58EQWFrMBS05DLHHVTViiA&oh=38aac0f19e909a7f293e55f59adfac4f&oe=5A6582E9" alt="Card image cap">
              <div class="card-body">
                <h4 class="card-title">Card title</h4>
                <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
              </div>
              <div class="card-footer">
                <small class="text-muted">Last updated 3 mins ago</small>
              </div>
            </div>
            <div class="card">
              <img class="card-img-top" src="https://scontent.fbkk2-6.fna.fbcdn.net/v/t31.0-8/17349680_1270129269743347_1004904647589363851_o.jpg?_nc_eui2=v1%3AAeFmEcY71k_SgiOeuQ9EKz5PWLntphZ2ykWNpb8aDQU9uC2UIiTd9I6kFkmuReZrRQZsWP-6c2sqRHHbs_OsrR6YHE3DqS8ldW1h1OLes5PrsA&oh=bc9c38788bd45c9b176f40c101beb0e0&oe=5A67FA76" alt="Card image cap">
              <div class="card-body">
                <h4 class="card-title">Card title</h4>
                <p class="card-text">This card has supporting text below as a natural lead-in to additional content.</p>
              </div>
              <div class="card-footer">
                <small class="text-muted">Last updated 3 mins ago</small>
              </div>
            </div>
            <div class="card">
              <img class="card-img-top" src="https://scontent.fbkk2-6.fna.fbcdn.net/v/t1.0-9/17498441_439526039723379_5714244413577316438_n.jpg?_nc_eui2=v1%3AAeEjpU_uV_5yu7yumVT0XythoTYYlWFsspE9xk9uQIkfcuN4C0OAH0y5-LNQu4bUQScc97XYzkdedmnzxCZdvAOpuFYVLWljeNT7uw8VYNF-FA&oh=933b65d7497386bbdb5015adee1be3d0&oe=5A729182" alt="Card image cap">
              <div class="card-body">
                <h4 class="card-title">Card title</h4>
                <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This card has even longer content than the first to show that equal height action.</p>
              </div>
              <div class="card-footer">
                <small class="text-muted">Last updated 3 mins ago</small>
              </div>
            </div>
            </div>
          </div>
          </div>
          <hr>
      <footer>
        <center>
        Software Engineering  @Walailak University
      </center>
      <br>
      </footer>
