<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>
        Search activity
    </h1>
    <p>
        <?php echo $this->tag->linkTo(["activity/new", "Create activity"]) ?>
    </p>
</div>

<?php echo $this->getContent() ?>

<?php
    echo $this->tag->form(
        [
            "activity/search",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldActivityid" class="col-sm-2 control-label">Activityid</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["activityid", "type" => "number", "class" => "form-control", "id" => "fieldActivityid"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldActivityname" class="col-sm-2 control-label">Activityname</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["activityname", "size" => 30, "class" => "form-control", "id" => "fieldActivityname"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldActivitydescription" class="col-sm-2 control-label">Activitydescription</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["activitydescription", "size" => 30, "class" => "form-control", "id" => "fieldActivitydescription"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldActivitydate" class="col-sm-2 control-label">Activitydate</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["activitydate", "type" => "date", "class" => "form-control", "id" => "fieldActivitydate"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldActivityplace" class="col-sm-2 control-label">Activityplace</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["activityplace", "size" => 30, "class" => "form-control", "id" => "fieldActivityplace"]) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Search", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
