<head>
    <link rel="stylesheet" href="../css/bootstrap.min.css">
  <style media="screen">
    .sty{
      background-size: contain;
      background-image: url(http://freedesignfile.com/upload/2013/02/Cartoon-City-Landscape-vector-01.jpg);
    }
  </style>
</head>

  <nav class="navbar navbar-expand-lg navbar-light" style="background-color:White;">

  <div class="container">
  <a class="navbar-brand" href="index"><img src="https://image.flaticon.com/icons/svg/552/552263.svg" class="img-fluid" alt="Responsive image" width="30"> &nbsp;ActivitySWE</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

      <li class="nav-item">
      <a class="nav-link" href="<?=$this->url->get("activity/index"); ?>">หน้าหลัก <span class="sr-only">(current)</span></a>
      </li>

      <li class="nav-item">
        <a class="nav-link" href="<?=$this->url->get("activity/new"); ?>">เพิ่มกิจกรรมนักศึกษา<span class="sr-only">(current)</span></a>
      </li>
    &nbsp;
    <img src="https://image.flaticon.com/icons/svg/149/149995.svg" alt="Responsive image" class="rounded-circle" width="4%"> &nbsp; User :  &nbsp;   &nbsp;Admin   &nbsp;  &nbsp;
    <li class="nav-item">
        <a class="btn btn btn btn-danger my-2 my-sm-0" href="<?=$this->url->get("#/index"); ?>">ออกจากระบบ</a>
    </li>
  </div>
</div>
</nav>
<div class="sty">
  <br><br><br><br><br><br><br><br><br><br><br>
</div>


      <?php echo $this->getContent(); ?>
