<head>
  <style media="screen">
    .sty{
      background-size: contain;
      background-image: url(http://freedesignfile.com/upload/2013/02/Cartoon-City-Landscape-vector-01.jpg);
    }
  </style>
</head>
<!-- <nav class="navbar navbar-expand-lg navbar-light bg-light"> -->
  <nav class="navbar navbar-expand-lg navbar-light" style="background-color:White;">

  <div class="container">
  <a class="navbar-brand" href="#"><img src="https://image.flaticon.com/icons/svg/552/552263.svg" class="img-fluid" alt="Responsive image" width="30"> &nbsp;ActivitySWE</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="ค้นหา" aria-label="Search">
      <button class="btn btn btn-light my-2 my-sm-0" type="submit">ค้นหา</button>
    </form>
    &nbsp;
    
    <li class="button">
        <a class=" btn btn btn-success " href="<?=$this->url->get("activity/#"); ?> type="submit"">เข้าสู่ระบบ</a>
    </li>
  </div>
</div>
</nav>
<div class="sty">
  <br><br><br><br><br><br><br><br><br><br><br>
</div>
  <?php echo $this->getContent(); ?>
