<head>
  <style media="screen">
    .sty{
      background-size: contain;
      background-image: url(http://freedesignfile.com/upload/2013/02/Cartoon-City-Landscape-vector-01.jpg);
    }
  </style>
</head>
<!-- <nav class="navbar navbar-expand-lg navbar-light bg-light"> -->
  <nav class="navbar navbar-expand-lg navbar-light" style="background-color:#52a2d5;">

  <div class="container">
  <a class="navbar-brand" href="#">ActivitySWE</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <!-- <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li> -->
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="ค้นหา" aria-label="Search">
      <button class="btn btn btn-light my-2 my-sm-0" type="submit">ค้นหา</button>
    </form>
    &nbsp;
    <button class="btn btn btn-success my-2 my-sm-0" type="submit">เข้าสู่ระบบ</button>
  </div>
</div>
</nav>
<div class="sty">
  <br><br><br><br><br><br><br><br><br><br><br>
</div>
  <?php echo $this->getContent(); ?>
